### ISSUE TITLE
Errors when the groups component is not active

### ISSUE THREAD

**Issue by renatonascalves** [buddypress/bp-blocks#19]
When the `groups` component is not active, we get an error when mounting the `Sidebar` component for the activity block editor. Mainly because of the endpoint: `/buddypress/v1/groups/me?context=edit`  is not available when that component is not active.

We don't get any visual regression but we do get an error in the console and a 404 request to that endpoint.

**Comment by imath** [comment]
It's a minor one. A possible way to prevent it would be to preload the request that checks active components.

**Comment by imath** [comment]
Fixed in https://github.com/buddypress/bp-blocks/commit/cdbab0ddf97e1ece8d46b40bd3c991c4abd967b9
