### ISSUE TITLE
Group block sketches

### ISSUE THREAD

**Issue by karmatosed** [buddypress/bp-blocks#2]
I began to think how the group block could work. I think staying simple makes sense here. A few points:

1. Use placeholder to pick group: a simple step that other blocks use of the placeholder being a way to select (see navigation block ).
2. The sidebar in v1 probably won't be used but could contain presentation (secondary) options that don't matter but could be nice. Worth noting it's important to not fill this up with multiple inputs the same like switches.

For the start of this I am keeping it super rough:

![image](https://user-images.githubusercontent.com/253067/71765882-b06ab280-2ef1-11ea-9aac-b2ad371671c1.png)

This block just displays the cover image and name of the group. I would like us to consider what the use is, for example, would we want to show invitations to join or maybe a click-through, or is it to also go as far as showing group activity? Maybe there are 2 blocks here, one for group profile and one for group activity?

**Comment by renatonascalves** [comment]
That's nice! A few thoughts:

- At the moment, both the users and the groups components have support to cover and profile/avatar images/attachments. I'd like us to make something that would accomodate both or any of them, as there are communities using one or the other. Both of them could use placeholders (as it is already used in the normal theme), but visually, it'd be good if they could "match" on the block.

- Having the cover or profile image and the group title, linking to the group itself seems like a first pass. However, now we are going to enter in a place of necessities. Communities necessity. Some would like to have the total number of members in the group in the block, or the total number of activities, or adding the group title and also the group moderator with their information, etc.

I'm not saying we should add those things. Only that the block should be flexible enough, visually, that adding those information (I presume this will be a dynamic block), will not be much of a hassle.

- One last note about the picker. I wonder if it should be a search input though. For communities with hundreds of groups, that would be easier and more performant.

--

Now to your questions.

> would we want to show invitations to join or maybe a click-through,

This seems like a good idea. Having a checkbox in the sidebar to hide/show this would be ideal.

> or is it to also go as far as showing group activity?

I'd think not. But we can see requests to show a "preview", kind of like the recent 10 activities, or the latest 10 forum topics of a group, etc. I however don't know the demand for this, so I'd label it as nice-to-have. 

> Maybe there are 2 blocks here, one for group profile and one for group activity?

I'm not sure if it deserves a second block. Doing in a way that it inserts into the group block and is left out without loss to the layout, I could see something similar to the invitation idea you brought it up.

Meaning, I can click an option in the sidebar and have a feed of activitiy or group forum topics. I know the idea is not to overflow the sidebar with settings, but I don't see the need for a second block for something that would be better served together with the main block.

Anyway, my suggestion of an approach would be to have a block like a transformer, where one could put or remove part of blocks in without disrupting everything.
:)

**Comment by imath** [comment]
Thanks @karmatosed for your work on this and thanks @renatonascalves for your feedback.

Here are my thoughts:
- I agree with Renato about the dropdown control we should probably use an autocomplete control. I can imagine considering the block will be available within the editor, admins will be able to list all `! hidden` groups of the community site.
- for a first version let’s keep it simple : Group Name linked to the group’s page, Group Description, avatar, cover.
- the settings sidebar can be used as Tammie suggested to hide/show all properties of my previous point except the group name.
- in the future: I see a great interest in displaying the number of group members and action buttons like Visit or Join.

I believe « Group Activities » is another block 😉

**Comment by imath** [comment]
As @renatonascalves requested, I've used a PR instead of directly committing. Thanks in advance for your feedbacks.

**Comment by imath** [comment]
Closing this as the block has been merged into BP Core
> https://buddypress.trac.wordpress.org/ticket/8048
