### ISSUE TITLE
Allow to give up on editing embed activity block

### ISSUE THREAD

**Issue by renatonascalves** [buddypress/bp-blocks#20]
Looking at how the embed activity block is working currently, there is no way for a person to give up on after selecting to edit it.

Here are the UAT steps:

- Create an embed activity block
- Paste the URL of an activity
- Click embed
- Click `Edit URL` in the block toolbar
- Now you can only add another, or the same, activity URL but you can't go back to the one before
- If you reload the page, your previous activity is lost

![Screen Shot 2020-09-13 at 2 56 23 PM](https://user-images.githubusercontent.com/19148962/93025142-e9efd380-f5d1-11ea-91fb-ba446803ba32.png)

I looked at another embed, Twitter, and the behavior is more in line with that I'm thinking we should adopt here: that the previous URL is there in case the person gives up on changing it:

![Screen Shot 2020-09-13 at 3 02 15 PM](https://user-images.githubusercontent.com/19148962/93025179-389d6d80-f5d2-11ea-85c7-dd6bff740ae1.png)

**Comment by imath** [comment]
I agree we should try to do like other embed blocks.
