### ISSUE TITLE
Allow users to list & manage their activities in WP admin screen

### ISSUE THREAD

**Issue by imath** [buddypress/bp-blocks#22]
We should improve this screen adding a view to see scheduled activities.

We should let users edit their activities from this screen as a start.

The Activity post form would replace the current Activity edit screen.

First stage of the activity post form should only make this new post form from the WP Admin context and let developers eventually add it on front end.

**Comment by derintolu** [comment]
hi there. As Gutenberg is about empowering end-users could you possibly rethink the last part. I personally would love to see a day where buddypress templates can be fully edited with the block editor. Also I can't imagine any users will use the backend Actitiy post forms. Most siteowners try as hard as they can to keep users out of the admin. I'm wondering if Have you seen this repo...https://github.com/Automattic/gutenberg-everywhere/. The block editor for every text field in wordpress is a bit much, but I really like it in the activity field and it bbpress.  It works quite well already. Just needs some CSS love. I think it would work great as another feature plugin.

**Comment by imath** [comment]
Hi @derintolu !

Thanks for linking the Automattic repository, I wasn't aware of it. I'm going to test it asap!!!

We already worked on a Block Activity Post Form, and yes I had this idea in a corner of my brain. Now it will be easier to create and publish BuddyPress Add-ons for feature as plugins, there's a good chance you'll be soon able to test the feature 😇.

The only thing I lack is time to work on it, or contributors to help me progress, but I feel it's the direction to take, I agree 👌
