### ISSUE TITLE
User profile block

### ISSUE THREAD

**Issue by karmatosed** [buddypress/bp-blocks#3]
This builds on from group block sketch in #2 and sees what a profile for user block could be. I can see this block being super useful for people and they even might want to call in from other sites (potentially in future).

![image](https://user-images.githubusercontent.com/253067/71765922-0e979580-2ef2-11ea-939c-613930fea231.png)

It's following the same simple process:
1. Placeholder to pick (we could do a smart default of existing user logged in).
2. Presentation in secondary.

**Comment by imath** [comment]
Hi @karmatosed 

Thanks a lot for your work on the sketches. I agree it could be super helpful 😊. This block could be used to display our profiles.wordpress.org « card » in the future.

To start with local profiles, I really like it. Some thoughts:
- I think we could use a custom autocomplete component extending the one provide by Gutenberg. I believe some communities might have a lot of members and the dropdown might not suit these communities.
- I imagine the settings sidebar of the block would include options to show hide the avatar/cover image.
- I can imagine some users might want to include some xprofile fields.. Let’s keep it simple for 1st version. Having cover, avatar, username linked to the profile page, and the display name is nice.
- Should we include some actions button like : View profile, Mention, Send à private message ?

**Comment by imath** [comment]
Hi!

In the above commit, I've made a first step in building the block. Here's how the placeholder looks:
![placeholder](https://user-images.githubusercontent.com/1834524/73126593-f547ad80-3fb4-11ea-9069-b460789bf9b3.png)

Then, once the member is selected, here's how the rendered block look:
![rendered](https://user-images.githubusercontent.com/1834524/73126604-114b4f00-3fb5-11ea-8011-86f0443046b9.png)

There are some other steps to achieve:
- Make the Autocomplete control more generic so it can be used by any BP Block.
- Add an edit button and alignments buttons to the block toolbar.
- Add settings to disable the avatar, etc.. (Sidebar secondary in the sketch)
- Improve the rendered block style and implement the Cover image feature.

**Comment by imath** [comment]
The commit above is adding a sidebar for the block settings. Here's a screen capture:
<img width="1042" alt="sidebar" src="https://user-images.githubusercontent.com/1834524/73593381-efe1ea00-4503-11ea-8ca4-e29e1f8bfcec.png">

**Comment by imath** [comment]
In 6f01bca571b18c555c9df9fbb310c0bf883ca265 I've added the cover image. Here are some screen captures of it:

<img width="596" alt="avatar-full" src="https://user-images.githubusercontent.com/1834524/73596807-0600a200-4526-11ea-9b43-d473f6903c1d.png">
**With a full size avatar.**

<img width="590" alt="avatar-thumb" src="https://user-images.githubusercontent.com/1834524/73596820-1add3580-4526-11ea-89f9-4aa450f11a9c.png">
**With a thumb size avatar.**

<img width="582" alt="avatar-none" src="https://user-images.githubusercontent.com/1834524/73596827-27618e00-4526-11ea-8875-a2430316d65f.png">
**With no avatar.**

**Comment by renatonascalves** [comment]
This looks great!

The only suggestion I'd add for future blocks is to add via a PR.

**Comment by imath** [comment]
Closing this as the block has been merged into BP Core
> https://buddypress.trac.wordpress.org/ticket/8048
