### ISSUE TITLE
German translation created...

### ISSUE THREAD

**Issue by M3Du5AL3M** [buddypress/bp-blocks#64]
I've translated the *.pot file to German and created bp-search-block-de_DE.po and bp-search-block-de_DE.mo files.
If anybody is interested in, I've attached the files here.
[bp-search-block-de_DE.zip](https://github.com/buddypress/bp-blocks/files/7974483/bp-search-block-de_DE.zip)

**Comment by imath** [comment]
Nice! Thanks a lot, I'll add it to the built plugin on WP repository.

**Comment by Soean** [comment]
@M3Du5AL3M Some remarks and improvements:

This translations are not correct:
- `Blogs` -> `Beiträge`
- `Posts` -> `Kommentare `
- Sometimes you use `Such ...` and sometimes `Suche ...`
- `Deine/Deiner` should be lowercase
- `Site` should be translated with `Website` not `Seite`

Maybe the [Styleguide](https://de.wordpress.org/mitwirken/style-guide-fuer-uebersetzungen/) and [Glossar](https://translate.wordpress.org/locale/de/default/glossary/) helps you a little bit to translate more consistent.

**Comment by M3Du5AL3M** [comment]
>

**Comment by M3Du5AL3M** [comment]
> * `Blogs` -> `Beiträge`
There's no official counterpart for `Blogs` in Wordpress, but I assumed the meaning was `Posts` and therefor the translation in German Wordpress is `Beiträge`
> * `Posts` -> `Kommentare `
You`re right, mistake by me, it should be also translated with `Beiträge`.
> * Sometimes you use `Such ...` and sometimes `Suche ...`
Not Sometimes, ONE time I used `Such ...`and that's in the Options. The translation makes more sense here for a german native speaker, for sure.
> * `Deine/Deiner` should be lowercase
If you form a saltuation to an unknown person, in Germany we have a wrtiting rule, where the first Letter has to be written in Uppercase. Looks more formally and respectfully for us.
> * `Site` should be translated with `Website` not `Seite`
Ok, `Webseite` should be better in German.
